#cloud-config
timezone: Europe/Berlin
package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - gnupg
write_files:
  - path: /home/os4user/my-config.yml
    permissions: '0644'
    content: |
      ---
      host: 0.0.0.0
      port: 443
      enableAutoHTTPS: true
      enableLocalHTTPS: false
      services:
        proxy:
          environment:
            EXTERNAL_ADDRESS: subdomain.pfadfinden.de
        backendAction:
          environment:
            EMAIL_HOST: smtpHostHier.pfadfinden.de
            EMAIL_PORT: 587
            EMAIL_HOST_USER: "mailAddyHier@pfadfinden.de"
            EMAIL_HOST_PASSWORD: ''
            EMAIL_CONNECTION_SECURITY: "STARTTLS"  # This can also be "NONE" or "STARTTLS".
            EMAIL_TIMEOUT: 5  # Timeout in seconds for blocking operations like the connection attempt.
            EMAIL_ACCEPT_SELF_SIGNED_CERTIFICATE: "false"  # Or "true" of course.
            DEFAULT_FROM_EMAIL: "mailAddyHier@pfadfinden.de"
      defaultEnvironment:
        SYSTEM_URL: subdomain.pfadfinden.de
    owner: os4user:os4user
runcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt update
  - apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - wget -P /home/os4user https://github.com/OpenSlides/openslides-manage-service/releases/download/latest/openslides
  - chmod +x /home/os4user/openslides
  - /home/os4user/openslides setup --config /home/os4user/my-config.yml /home/os4user
  - sed -i '/      - 0.0.0.0:443:8000/i\      - 0.0.0.0:80:8001' /home/os4user/docker-compose.yml
  - docker compose -f /home/os4user/docker-compose.yml pull
  - docker compose -f /home/os4user/docker-compose.yml up -d
  - sleep 60
  - cd /home/os4user
  - /home/os4user/openslides initial-data -a subdomain.pfadfinden.de:443
  - chown -R os4user:os4user /home/os4user
